-- *************************
-- AC ORACLE
-- *************************

-- **** DEFINITON DES STRUCTURES

DROP TABLE LIVRE
/
CREATE TABLE LIVRE (
IdLivre INTEGER,
TitreLivre VARCHAR(30) NOT NULL
)
/
ALTER TABLE LIVRE
ADD CONSTRAINT PK_LIVRE PRIMARY KEY(IdLivre)
/


DROP TABLE EXEMPLAIRES_LIVRE
/
CREATE TABLE EXEMPLAIRES_LIVRE (
IdExemplaire INTEGER,
IdLivre INTEGER,
AnneeEdition INTEGER
)
/
ALTER TABLE EXEMPLAIRES_LIVRE
-- ADD CONSTRAINT PK_EXEMPLAIRES_LIVRE PRIMARY KEY(IdExemplaire)

-- Correction
ADD CONSTRAINT PK_EXEMPLAIRES_LIVRE PRIMARY KEY(IdExemplaire, IdLivre)
ADD CONSTRAINT FK_EXEMPLAIRES_LIVRE FOREIGN KEY(IdLivre) REFERENCES LIVRE(IdLivre) ON DELETE CASCADE
/

-- *** Jeu de données

INSERT INTO LIVRE (IdLivre, TitreLivre) VALUES (1, 'L''ETRANGER')
/
INSERT INTO LIVRE (IdLivre, TitreLivre) VALUES (2, 'LE PARFUN')
/
INSERT INTO LIVRE (IdLivre, TitreLivre) VALUES (3, 'HARRY POTTER')
/

INSERT INTO EXEMPLAIRES_LIVRE (IdExemplaire,IdLivre,AnneeEdition) VALUES (3,3, 1993)
/
INSERT INTO EXEMPLAIRES_LIVRE (IdExemplaire,IdLivre,AnneeEdition) VALUES (1,2, 1988)
/
INSERT INTO EXEMPLAIRES_LIVRE (IdExemplaire,IdLivre,AnneeEdition) VALUES (2,2, 1999)
/

-- ** Requêtes générant les anomalies

INSERT INTO EXEMPLAIRES_LIVRE (IdExemplaire,IdLivre,AnneeEdition) VALUES (1,1, 2000)
/
DELETE LIVRE WHERE TitreLivre='HARRY POTTER';


SELECT * FROM LIVRE;
SELECT * FROM EXEMPLAIRES_LIVRE;