-- SCRIPT GESTION DES MARCHES

DROP TABLE MARCHE CASCADE CONSTRAINT;
CREATE TABLE MARCHE(
   IdMarche NUMBER(10),
   NomMarche VARCHAR2(50) NOT NULL,
   CONSTRAINT PK_MARCHE PRIMARY KEY(IdMarche)
);

DROP TABLE EMPLACEMENT CASCADE CONSTRAINT;
CREATE TABLE EMPLACEMENT(
   IdMarche NUMBER(10),
   NoEmplacement NUMBER(10),
   NoAllee NUMBER(10) NOT NULL,
   Metrage NUMBER(10) NOT NULL,
   CONSTRAINT PK_EMPLACEMENT PRIMARY KEY(NoEmplacement),
   CONSTRAINT FK_EMPLACEMENT_MARCHE FOREIGN KEY(IdMarche) REFERENCES MARCHE(IdMarche)
);

DROP TABLE MARCHAND CASCADE CONSTRAINT;
CREATE TABLE MARCHAND(
   IdMarchand NUMBER(10),
   NomMarchand VARCHAR2(50) NOT NULL,
   CONSTRAINT PK_MARCHAND PRIMARY KEY(IdMarchand)
);


DROP TABLE ANNEE CASCADE CONSTRAINT;
CREATE TABLE ANNEE(
   Annee VARCHAR2(50),
   CONSTRAINT PK_ANNEE PRIMARY KEY(Annee)
);

DROP TABLE RESERVE CASCADE CONSTRAINT;
CREATE TABLE RESERVE(
   IdMarche NUMBER(10),
   NoEmplacement NUMBER(10),
   Annee VARCHAR2(50),
   IdMarchand NUMBER(10) NOT NULL,
   CONSTRAINT PK_RESERVE PRIMARY KEY(IdMarche, NoEmplacement, Annee, IdMarchand),
   CONSTRAINT FK_RESERVE_EMPLACEMENT FOREIGN KEY(IdMarche, NoEmplacement) REFERENCES EMPLACEMENT(IdMarche, NoEmplacement),
   CONSTRAINT FK_RESERVE_ANNEE FOREIGN KEY(Annee) REFERENCES ANNEE(Annee),
   CONSTRAINT FK_RESERVE_MARCHAND FOREIGN KEY(IdMarchand) REFERENCES MARCHAND(IdMarchand)
);

